apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: orgmarcel/frontendbuild:latest  # Replace with your Docker image for the frontend
        ports:
        - containerPort: 8081  # Port where the frontend service listens
