
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081  # Map Kubernetes Service port 80 to container port 8081
  type: NodePort  # Use ClusterIP to make the service accessible within the cluster
