apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Map Kubernetes Service port 80 to container port 8080
  type: ClusterIP  # Use ClusterIP to make the service accessible within the cluster